### ISSUE TITLE
False-positive validation error on $ref-linked arrays

### ISSUE THREAD

**Issue by mike-sierra** [Gi60s/openapi-enforcer#138]
I detected what's apparently a false-positive validation error. When you $ref-link to an array, such as a common enum set, you get this validation message: `Value must be an array. Received: true`

**Comment by Gi60s** [comment]
Thanks for the issue. I'll take a look.

Also, if you have an example OpenAPI document that will help me to debug and fix it. If not I'll try to recreate the problem myself.

**Comment by Gi60s** [comment]
I'm not able to replicate the issue. Can you share an example with me?

**Comment by Gi60s** [comment]
I found an error that may be related to what you were seeing. I've pushed a change to NPM with version 1.19.0. Check it out and let me know if it fixed the problem for you.
