### ISSUE TITLE
Ignore "Property not allowed"

### ISSUE THREAD

**Issue by AndrewChurchill** [Gi60s/openapi-enforcer#140]
Hello, is there a way to ignore "Property not found" errors during document validation? For example:

```JavaScript
const [openapi, error, warning] = await Enforcer(path, {
    fullResult: true,
    componentOptions: {
        exceptionSkipCodes: [
            // Don't warn for non-standard format types
            'WSCH001',

            // Don't check "example" properties
            'WSCH006',
        ],
    },
});
```

When called, the error will be:
```
One or more errors exist in the OpenApi definition
  at: components > schemas > somethingV1 > properties
    at: somethingElseV1 > properties
      at: id
        Property not allowed: readonly
      at: myProperty
        Property not allowed: readonly
      at: myOtherProperty
        Property not allowed: readonly
    at: version > properties > someProperty
      Property not allowed: additionalProperties
```

We would like to allow properties like "readonly" and "additionalProperties" even though they don't quite conform to the spec. Is there a way to ignore this step of the document validation entirely?

Thank you for your help!

**Comment by Gi60s** [comment]
You can now use properties that are not part of the actual spec by specifying the exception skip code `EDEV001`. If you are unfamiliar with the way skip codes work please see this documentation: https://openapi-enforcer.com/api/#enforcer

This has been published to NPM with version `1.21.0`.

Have a great day!

**Comment by Gi60s** [comment]
I believe you are specifying the code correctly. I'll check this out. Also, if you have an example `openapi.yml` or other file that I could run it against that will help to ensure that I've fixed the problem.

**Comment by plankthom** [comment]
@Gi60s I've run in this to: it seems as if the `exceptionSkipCodes` options are not respected.

The debugger pointed to 
https://github.com/Gi60s/openapi-enforcer/blob/fc78fe42b4cf2eba9200188cc8d45f8aaadf1577/src/definition-validator.js#L388
which in this case creates a `new Schema(new ValidatorState(data))` using constructor helper
https://github.com/Gi60s/openapi-enforcer/blob/fc78fe42b4cf2eba9200188cc8d45f8aaadf1577/src/super.js#L79

The user options are carried in the `definition.options` but not used and `options` is not set ...

**Comment by plankthom** [comment]
A test case:

[openapi-enforcer-140.zip](https://github.com/Gi60s/openapi-enforcer/files/9785415/openapi-enforcer-140.zip)

**Comment by Gi60s** [comment]
Thanks for your patience. This should be fixed now. Try version `1.22.1`.
